name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup VS Dev Environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Restore NuGet packages
      run: nuget restore win-clip.sln

    - name: Build solution
      run: |
        msbuild win-clip.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=x64 /p:WarningLevel=3 /verbosity:minimal

    - name: Upload artifacts
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: win-clip-x64-${{ matrix.configuration }}
        path: |
          x64/${{ matrix.configuration }}/win-clip.exe
        if-no-files-found: ignore
